export const SET_ARTICLES = 'SET_ARTICLES';
export const SELECT_ID = 'SELECT_ID';
export const SET_PREVIEW_VISIBILITY = 'SET_PREVIEW_VISIBILITY';
export const SET_EDITOR_VISIBILITY = 'SET_EDITOR_VISIBILITY';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
